name: Crystal
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/crystal.yml
      - languages/crystal/**
  schedule:
    - cron:  25 3 * * MON
jobs:
  latest:
    uses: ./.github/workflows/publish-image.yml
    with:
      version: latest
      language: crystal
      description: Devcontainer for Crystal with Crystalline
    secrets:
      registry_username: ${{ secrets.DOCKER_USERNAME }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}
