name: Crystal
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/crystal.yml
      - languages/crystal/**
  schedule:
    - cron:  25 3 * * MON
env:
  LANGUAGE: crystal
  REPOSITORY: metio/devcontainers
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      security-events: write
    strategy:
      matrix:
        version: ["latest"]
    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v3
      - id: cosign
        name: Install Cosign
        uses: sigstore/cosign-installer@main
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: dockerhub_login
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: timestamp
        name: Create Timestamp
        run: echo "::set-output name=date::$(date --rfc-3339=seconds)"
      - id: publish
        name: Publish Image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./languages/${{ env.LANGUAGE }}/${{ matrix.version }}/
          file: ./languages/${{ env.LANGUAGE }}/${{ matrix.version }}/Containerfile
          push: true
          tags: docker.io/${{ env.REPOSITORY }}-${{ env.LANGUAGE }}:${{ matrix.version }}
          labels: |
            org.opencontainers.image.title=${{ env.LANGUAGE }}
            org.opencontainers.image.description=Image for ${{ env.LANGUAGE }} development
            org.opencontainers.image.licenses=CC0-1.0
            org.opencontainers.image.vendor=metio.wtf
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/languages/${{ env.LANGUAGE }}/${{ matrix.version }}
            org.opencontainers.image.version=${{ matrix.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.timestamp.outputs.date }}
          cache-from: type=registry,ref=${{ env.REPOSITORY }}-${{ env.LANGUAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.REPOSITORY }}-${{ env.LANGUAGE }}:buildcache,mode=max
      - id: sign
        name: Sign Image
        run: cosign sign docker.io/${{ env.REPOSITORY }}-${{ env.LANGUAGE }}@${{ steps.publish.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: "true"
      - id: sbom
        name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: docker.io/${{ env.REPOSITORY }}-${{ env.LANGUAGE }}@${{ steps.publish.outputs.digest }}
          artifact-name: sbom-spdx.json
          dependency-snapshot: true
      - id: sbom-attest
        name: Attest SBOM
        run: cosign attest --predicate sbom-spdx.json --type spdx docker.io/${{ env.REPOSITORY }}-${{ env.LANGUAGE }}@${{ steps.publish.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: "true"
      - id: scan
        name: Scan SBOM
        uses: anchore/scan-action@v3
        with:
          image: sbom-spdx.json
          acs-report-enable: true
          fail-build: false
      - id: sarif
        name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
          category: ${{ env.LANGUAGE }}-${{ matrix.version }}
      - id: documentation
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.REPOSITORY }}-${{ env.LANGUAGE }}
          short-description: Devcontainer for Crystal with Crystalline
          readme-filepath: ./languages/${{ env.LANGUAGE }}/README.md
