name: Crystal
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/crystal.yml
      - languages/crystal/**
  schedule:
    - cron:  25 3 * * MON
env:
  LANGUAGE: crystal
  DESCRIPTION: Devcontainer for Crystal with Crystalline
permissions:
  contents: write
  id-token: write
  security-events: write
jobs:
  latest:
    uses: ./.github/workflows/publish-image.yml
    with:
      version: latest
      language: ${{ env.LANGUAGE }}
      description: ${{ env.DESCRIPTION }}
      registry_username: ${{ secrets.DOCKER_USERNAME }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}
