name: Crystal
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/crystal.yml
      - languages/crystal/**
  schedule:
    - cron:  25 3 * * MON
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["latest"]
    steps:
      - uses: ./.github/workflows/publish-image.yml
        with:
          language: crystal
          version: ${{ matrix.version }}
          description: Devcontainer for Crystal with Crystalline
