name: Elixir
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/python.yml
      - languages/elixir/**
  schedule:
    - cron:  15 3 * * MON
env:
  LANGUAGE: elixir
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        version: ["1.10", "1.11", "1.12", "latest"]
    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v3
      - id: cosign
        name: Install Cosign
        uses: sigstore/cosign-installer@main
      - id: syft
        name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.11.0
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: login
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: timestamp
        name: Create Timestamp
        run: echo "::set-output name=date::$(date --rfc-3339=seconds)"
      - id: publish
        name: Publish Image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./languages/${{ env.LANGUAGE }}/${{ matrix.version }}/
          file: ./languages/${{ env.LANGUAGE }}/${{ matrix.version }}/Containerfile
          push: true
          tags: ghcr.io/metio/devcontainers/${{ env.LANGUAGE }}:${{ matrix.version }}
          labels: |
            org.opencontainers.image.title=${{ env.LANGUAGE }}
            org.opencontainers.image.description=Image for ${{ env.LANGUAGE }} development
            org.opencontainers.image.licenses=CC0-1.0
            org.opencontainers.image.vendor=metio.wtf
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/languages/${{ env.LANGUAGE }}/${{ matrix.version }}
            org.opencontainers.image.version=${{ matrix.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.timestamp.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - id: sign
        name: Sign Image
        run: cosign sign ghcr.io/metio/devcontainers/${{ env.LANGUAGE }}:${{ matrix.version }}
        env:
          COSIGN_EXPERIMENTAL: "true"
      - id: sbom
        name: Attach SBOM
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          syft ghcr.io/metio/devcontainers/${{ env.LANGUAGE }}:${{ matrix.version }} -o spdx-json=sbom-spdx.json
          cosign attest --predicate sbom-spdx.json --type spdx ghcr.io/metio/devcontainers/${{ env.LANGUAGE }}:${{ matrix.version }}
