name: Elixir
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/elixir.yml
      - languages/elixir/**
  schedule:
    - cron:  35 3 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "1.14", "1.13", "1.12", "1.11"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: elixir
      description: Devcontainer for Elixir with ElixirLS
    secrets: inherit
  provenance:
    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    with:
      image: docker.io/metio/devcontainers-elixir
      digest: "sha256:abcdefabcdefabcdefabcdef"
      registry-username: "${{ secrets.DOCKER_USERNAME }}"
    secrets:
      registry-password: "${{ secrets.DOCKER_PASSWORD }}"
