name: Java
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/java.yml
      - languages/java/**
  schedule:
    - cron:  35 4 * * MON
jobs:
  latest:
    uses: ./.github/workflows/publish-image.yml
    with:
      version: latest
      language: java
      description: Devcontainer for Java with JDT LS
    secrets: inherit
  version-8:
    name: "8"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "8"
      language: java
      description: Devcontainer for Java with JDT LS
    secrets: inherit
  version-11:
    name: "11"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "11"
      language: java
      description: Devcontainer for Java with JDT LS
    secrets: inherit
  version-17:
    name: "17"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "17"
      language: java
      description: Devcontainer for Java with JDT LS
    secrets: inherit
