name: Java
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/java.yml
      - languages/java/**
  schedule:
    - cron:  35 4 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "17", "11", "8"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: java
      description: Devcontainer for Java with JDT LS
    secrets:
      registry-username: ${{ secrets.DOCKER_USERNAME }}
      registry-password: ${{ secrets.DOCKER_PASSWORD }}
