name: Nix
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/nix.yml
      - languages/nix/**
  schedule:
    - cron:  15 5 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: nix
      description: Devcontainer for Nix with Nix Language Server
    secrets: inherit
