name: NodeJS
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/nodejs.yml
      - languages/nodejs/**
  schedule:
    - cron:  25 5 * * MON
jobs:
  latest:
    uses: ./.github/workflows/publish-image.yml
    with:
      version: latest
      language: nodejs
      description: Devcontainer for NodeJS with TypeScript Language Server
    secrets: inherit
  version-16:
    name: "16"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "16"
      language: nodejs
      description: Devcontainer for NodeJS with TypeScript Language Server
    secrets: inherit
  version-18:
    name: "18"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "18"
      language: nodejs
      description: Devcontainer for NodeJS with TypeScript Language Server
    secrets: inherit
