name: NodeJS (latest)
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/nodejs.yml
      - languages/nodejs/latest/**
  schedule:
    - cron:  15 3 * * MON
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
