name: NodeJS (latest)
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/nodejs.yml
      - languages/nodejs/latest/**
  schedule:
    - cron:  15 3 * * MON
env:
  LANGUAGE: nodejs
  VERSION: latest
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v3
      - id: cosign
        name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: v1.7.1
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: login
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: publish
        name: Publish Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./languages/${{ env.LANGUAGE }}/${{ env.VERSION }}/
          file: ./languages/${{ env.LANGUAGE }}/${{ env.VERSION }}/Containerfile
          push: true
          tags: ghcr.io/metio/dev-containers/${{ env.LANGUAGE }}:${{ env.VERSION }}
      - id: sign
        name: Sign Image
        run: |
          echo ${COSIGN_KEY} > cosign.key && \
          cosign sign --key cosign.key ghcr.io/metio/dev-containers/${{ env.LANGUAGE }}:${{ env.VERSION }}
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
