name: Prolog
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/prolog.yml
      - languages/prolog/**
  schedule:
    - cron:  45 5 * * MON
jobs:
  latest:
    uses: ./.github/workflows/publish-image.yml
    with:
      version: latest
      language: prolog
      description: Devcontainer for Prolog with Prolog Language Server
    secrets: inherit
  stable:
    uses: ./.github/workflows/publish-image.yml
    with:
      version: stable
      language: prolog
      description: Devcontainer for Prolog with Prolog Language Server
    secrets: inherit
