name: Publish Container Image
on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      version:
        required: true
        type: string
      description:
        required: true
        type: string
env:
  REPOSITORY: metio/devcontainers
  LICENSE: CC0-1.0
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      security-events: write
    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v3
      - id: cosign-install
        name: Install Cosign
        uses: sigstore/cosign-installer@main
      - id: syft-install
        name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.12.0
      - id: grype-install
        name: Install Grype
        uses: anchore/scan-action/download-grype@v3
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: dockerhub_login
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: timestamp
        name: Create Timestamp
        run: echo "::set-output name=date::$(date --rfc-3339=seconds)"
      - id: publish
        name: Publish Image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./languages/${{ env.LANGUAGE }}/${{ inputs.version }}/
          file: ./languages/${{ env.LANGUAGE }}/${{ inputs.version }}/Containerfile
          push: true
          tags: docker.io/${{ env.REPOSITORY }}-${{ env.LANGUAGE }}:${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=${{ env.LANGUAGE }}
            org.opencontainers.image.description=Image for ${{ env.LANGUAGE }} development
            org.opencontainers.image.licenses=${{ env.LICENSE }}
            org.opencontainers.image.vendor=metio.wtf
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/languages/${{ env.LANGUAGE }}/${{ inputs.version }}
            org.opencontainers.image.version=${{ inputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.timestamp.outputs.date }}
          cache-from: type=registry,ref=${{ env.REPOSITORY }}-${{ env.LANGUAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.REPOSITORY }}-${{ env.LANGUAGE }}:buildcache,mode=max
      - id: sign
        name: Sign Image
        run: cosign sign docker.io/${{ env.REPOSITORY }}-${{ env.LANGUAGE }}@${{ steps.publish.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: "true"
      - id: sbom
        name: Generate SBOM
        run: syft docker.io/${{ env.REPOSITORY }}-${{ env.LANGUAGE }}@${{ steps.publish.outputs.digest }} -o spdx-json=sbom-spdx.json
      - id: sbom-attest
        name: Attest SBOM
        run: |
          cosign attest \
            --predicate sbom-spdx.json \
            --type spdx \
            docker.io/${{ env.REPOSITORY }}-${{ env.LANGUAGE }}@${{ steps.publish.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: "true"
      - id: grype-scan
        name: Scan SBOM with Grype
        run: grype -o sarif --only-fixed sbom:sbom-spdx.json > grype.sarif
      - id: hadolint-scan
        name: Scan Containerfile with Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ./languages/${{ env.LANGUAGE }}/${{ inputs.version }}/Containerfile
          format: sarif
          output-file: hadolint.sarif
          no-fail: true
      - id: grype-upload
        name: Upload Grype SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: grype.sarif
          category: grype-${{ env.LANGUAGE }}-${{ inputs.version }}
      - id: hadolint-upload
        name: Upload Hadolint SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint.sarif
          category: hadolint-${{ env.LANGUAGE }}-${{ inputs.version }}
      - id: documentation
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.REPOSITORY }}-${{ env.LANGUAGE }}
          short-description: ${{ inputs.description }}
          readme-filepath: ./languages/${{ env.LANGUAGE }}/README.md
