name: Ruby
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/ruby.yml
      - languages/ruby/**
  schedule:
    - cron:  25 6 * * MON
jobs:
  latest:
    uses: ./.github/workflows/publish-image.yml
    with:
      version: latest
      language: ruby
      description: Devcontainer for Ruby with Ruby Language Server
    secrets: inherit
