name: Terraform
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/terraform.yml
      - languages/terraform/**
  schedule:
    - cron:  35 6 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: terraform
      description: Devcontainer for Terraform with Terraform Language Server
    secrets:
      registry-username: ${{ secrets.DOCKER_USERNAME }}
      registry-password: ${{ secrets.DOCKER_PASSWORD }}
