name: Terraform
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/terraform.yml
      - languages/terraform/**
  schedule:
    - cron:  35 6 * * MON
jobs:
  latest:
    uses: ./.github/workflows/publish-image.yml
    with:
      version: latest
      language: terraform
      description: Devcontainer for Terraform with Terraform Language Server
    secrets: inherit
